---
title: "League of Legends 2022 Match Data Analysis"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
```

```{r}
match_data_master <- read_csv("data/2022_match_data.csv")
```

A whole bunch of these columns can be logicals. `result` is a binary check for win/loss, all the first blood columns are to do with just identifying involvement, as is `firstdragon`, `firstherald`, `firstbaron`, and the three metrics surrounding first tower. Useful! Going to rename `result` as `winner` too, for better clarity, and snake_case all the column headers.

```{r}
match_data_master_adjusted <- match_data_master %>% 
    mutate(across(c(result, 
                    firstblood, 
                    firstbloodkill, 
                    firstbloodassist,
                    firstbloodvictim,
                    firstdragon,
                    firstherald,
                    firstbaron,
                    firsttower,
                    firstmidtower,
                    firsttothreetowers), ~as.logical(.x))) %>% 
    rename(c("winner" = "result", 
             "game_id" = "gameid",
             "data_completeness" = "datacompleteness",
             "paricipant_id" = "participantid",
             "player_name" = "playername",
             "player_id" = "playerid",
             "team_name" = "teamname",
             "team_id" = "teamid",
             "ban_1" = "ban1",
             "ban_2" = "ban2",
             "ban_3" = "ban3",
             "ban_4" = "ban4",
             "ban_5" = "ban5",
             "game_length" = "gamelength",
             "team_kills" = "teamkills",
             "team_deaths" = "teamdeaths",
             "double_kills" = "doublekills",
             "triple_kills" = "triplekills",
             "quadra_kills" = "quadrakills",
             "penta_kills" = "pentakills",
             "team_kpm" = "teamkpm",
             "c_kpm" = "ckpm",
             "elemental_drakes" = "elementaldrakes",
             "first_blood" = "firstblood", 
             "first_blood_kill" = "firstbloodkill",
             "first_blood_assist" = "firstbloodassist",
             "first_blood_victim" = "firstbloodvictim",
             "first_dragon" = "firstdragon",
             "first_herald" = "firstherald",
             "first_baron" = "firstbaron",
             "first_tower" = "firsttower",
             "first_mid_tower" = "firstmidtower",
             "first_to_three_towers" = "firsttothreetowers"
             ))
```