---
title: "R Notebook"
output: html_notebook
---



```{r}
library(tidyverse)
library(lubridate)

lec_data <- read_csv("data/lec_data.csv") %>% 
  mutate(game_id = as.factor(game_id))

lec_data_teams <- lec_data %>% 
  filter(is.na(player_name)) %>% 
  mutate(kda = ((kills + assists) / if_else(deaths == 0, 1, deaths))) %>% 
  relocate(kda, .after = assists) %>% 
  mutate(kda = round(kda, 2))

lec_data_players <- lec_data %>% 
  filter(!is.na(player_name)) %>% 
  mutate(kda = ((kills + assists) / if_else(deaths == 0, 1, deaths))) %>% 
  relocate(kda, .after = assists) %>% 
  mutate(kda = round(kda, 2))
  
```

```{r}
get_roster <- function(x_team){
  
  lec_data %>% 
    filter(!is.na(player_name), team_name == x_team) %>% 
    select(position, player_name, game_id) %>% 
    group_by(player_name) %>% 
    summarise(position, games = n_distinct(game_id)) %>% 
    distinct() %>% 
    ungroup() %>% 
    select(position, player_name, games) %>% 
    arrange(factor(position, levels = c("top", "mid", "bot", "sup", "jng")), player_name)
}

get_matches <- function(x_team){
  
  lec_data %>% 
    select(game_id, team_name) %>% 
    group_by(game_id) %>%
    filter(team_name == x_team) %>% 
    select(game_id) %>% 
    distinct() %>% 
    pull()
}

get_game_history <- function(x_team){
  
  team_games <- get_matches(x_team)
  
  lec_data %>% 
    select(game_id, date, split, playoffs, game, side, team_name, winner) %>% 
    filter(game_id %in% team_games, team_name != x_team) %>%
    distinct() %>% 
    mutate(winner = !winner) %>% 
    arrange(date, game)
}

get_match_history <- function(x_team, match_data){
  
  get_game_history(x_team) %>% 
    select(date, split, playoffs, game, team_name, winner) %>% 
    mutate(date = as.Date(date)) %>% 
    group_by(date) %>%
    count(team_name, playoffs, split, winner) %>% 
    pivot_wider(names_from = winner, values_from = n) %>% 
    rename(wins = `TRUE`, losses = `FALSE`) %>% 
    mutate(wins = coalesce(wins, 0), losses = coalesce(losses, 0),
           winner = if_else(wins > losses, TRUE, FALSE))
}

```

```{r}
no_games <- length(unique(na.omit(lec_data$game_id)))
no_teams <- length(unique(na.omit(lec_data$team_name)))
total_champs <- length(unique(na.omit(lec_data$champion)))
total_kills <- lec_data %>% 
  filter(is.na(player_name)) %>% 
  summarise(total_kills = sum(kills)) %>% 
  pull()
total_deaths <- lec_data %>% 
  filter(is.na(player_name)) %>% 
  summarise(total_deaths = sum(deaths)) %>% 
  pull()
top5_picks <- lec_data %>% 
  select(champion) %>% 
  filter(!is.na(champion)) %>% 
  group_by(champion) %>% 
  summarise(times_picked = n()) %>% 
  slice_max(times_picked, n = 5)
top5_bans <- 
  lec_data %>% 
  filter(is.na(player_name)) %>% 
    select(ban_1:ban_5) %>%
  pivot_longer(1:5, names_to = "ban_no", values_to = "champion") %>% 
  group_by(champion) %>% 
  summarise(times_banned = n()) %>% 
  slice_max(times_banned, n = 5)
```

```{r}
lec_data %>% 
  filter(is.na(player_name)) %>% 
    select(ban_1:ban_5) %>%
  pivot_longer(1:5, names_to = "ban_no", values_to = "champ") %>% 
  group_by(champ) %>% 
  summarise(times_banned = n()) %>% 
  slice_max(times_banned, n = 5)
```

```{r}
lec_data_players %>% 
  filter(team_name == "Fnatic",
         split == "Spring") %>% 
  ggplot() +
  geom_line(aes(x = date, y = deaths, group = player_name, colour = player_name)) +
  scale_x_date(date_breaks = "1 week",
               date_labels = "%d %B")
```

```{r}
lec_data_players %>% 
  filter(playoffs == TRUE,
         split == "Spring",
         player_name == "Odoamne") %>% 
  select(player_name, date)
```


```{r}
lec_data_teams %>% 
  ggplot() +
  geom_line(aes(x = game_id, y = kda, group = team_name, colour = team_name))
```


